<a href="https://colab.research.google.com/github/hamzafarooq/DataStructures-Algo/blob/master/Interview_query.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Palindrome for a number

In [ ]:
def plaindrome(num):
  if num <= 0:
    return num==0 #121
  i=num
  l=0
  total=0
  while i >0:
    digit=i%10
    total = total*(10)+digit
    i=i//10
  return total==num



In [ ]:
plaindrome(10001)


'10001'

In [ ]:
def plaindromstring(s):
  if len(s)==1:
    return True

  return s==s[::-1]

In [ ]:
plaindromstring('bzb')

True

## Reverse Bits

In [ ]:
def reversebits(x):
  output=0

  while x!=0:
    output = output << 1

    if x & 1 == 1:
      output |=1
    
    x = x >> 1
    #print(x)

  return output

In [ ]:
reversebits(9090)

4209

## Power of 2


In [ ]:
def powerof2(num):  
  if num <= 0:
    return False
  if num == 1:
    return True
  max = int(round(num/2,0))
  j=0
  for i in range(max+1):
    if i*i==num:
      j=1
    
  return (j==1)

In [ ]:
powerof2(121)

True

In [ ]:
round(6/2,0)

3.0

## Longest Substring without repeating
Given a string s, return the length of the longest substring of s without repeating characters.




In [ ]:
def substring(s):
  h={}
  maxlen=start=0

  for index,char in enumerate(s):
    if char in h and start <= h[char]:
      start=h[char]+1
    else:
      maxlen = max(maxlen, index-start+1)
    h[char]= index

  return maxlen

In [ ]:
substring("cc")

1

## Valid Parenthesis

In [ ]:
def valid(s):
  paren = {"(":")",
           "{":"}",
           "[":"]"
  }

  l=[]

  if not s:
    return True

  for i in range(len(s)):
    if s[i] in paren:
      l.append(s[i])

    elif not l: ## this happens in case of ()]
      return False
    
    else:
      if s[i]==paren[l[-1]]:  ## comparing the closing loop
        del l[-1]

      else:
        return False

  if not l:
    return True

In [ ]:
a="()[]{}}"

In [ ]:
valid(a)

False

## Rotate Matrix Left

In [ ]:
def rotleft(nums,k):
  k%=len(nums)
  nums[:]=nums[k:]+nums[:k]
  return(nums)

In [ ]:
rotleft(a,1)

array([[4, 6],
       [4, 6]])

## rotate matrix right


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
for i in range(len(a)-1):

  topleft=a[i,i]
  topright=a[0,len(a)-1]
  bottomleft = a[len(a)-1,0]  
  bottomright =a[len(a)-1,len(a)-1]

  a[0,0]=bottomleft
  a[1,0]=bottomright
  a[0,1]=topleft
  a[1,1]=topright

In [ ]:
len(a)

2

In [ ]:
def rotate(nums,k):
  k %= len(nums)
  print (k)
  nums[:] = nums[-k:] + nums[:-k]
  return nums

In [ ]:
rotate(a,5)

1


array([[32, 48],
       [32, 48]])

## Phone number

In [ ]:
def phonecheck(s):
  phonebook ={
            "2":["a","b","c"],
            "3":["d","e","f"],
            "4":["g","h","i"],
            "5":["j","k","l"],
            "6":["m","n","o"],
            "7":["p","q","r","s"],
            "8":["v","t","u"],
            "9":["w","x","y","z"]
            }
  l=[]
  for i in s:
    j=phonebook[i]
    l.append("".join(j))
    #l.append(phonebook[i])
  k="".join(l)
  return l
        
        

In [ ]:
phonecheck('2347')

['abc', 'def', 'ghi', 'pqrs']

## Target Indices

In [ ]:
def targetindicies(nums,target):
  l={}
  p=[]
  if len(nums)==1 and nums[0]!=target:
    return [0,0]

  for iter,char in enumerate(nums):
    diff=target-char
    if diff in l :
      p.append([l[diff],iter])
    else:
      l[char]=iter

  if not p:
    return [0,0]  
  return sorted(p)




In [ ]:

targetindicies([],6)

[0, 0]

## Bigrams

In [ ]:
def bigrams(a):
  a=a.split()
  l=[]
  h={}
  start=0
  end=0
  for i in range(len(a)-1):
    l.append([a[i],a[i+1]])
  

  return l
      

      

  

In [ ]:
bigrams('this is a long sentence')

[['this', 'is'], ['is', 'a'], ['a', 'long'], ['long', 'sentence']]

In [ ]:
a='this is a long sentence'

In [ ]:
a.split()

['this', 'is', 'a', 'long', 'sentence']

## Pattern Matching
Given a set of strings words and a string pattern return a list of all of the strings in words that matches the pattern of the pattern string.

In [ ]:
def patternmatch(words,pattern):
  k=words.split()
  d={}

  if len(pattern)!= len(k):
    return False
  
  for i in range(len(pattern)):
    if pattern[i] not in d and k[i] not in d.values():
      d[pattern[i]]=k[i]
    elif pattern[i] not in d:
      return False
    elif k[i] not in d.values():
      return False
    elif d[pattern[i]] != k[i]:
      return False

  return True
  


In [ ]:
patternmatch('cat dog dog cat','abba')

True

##Palindrome Permute


In [ ]:
def ispalindromebypermute(s): # first check if the string is a plaindrome from various permutations

  h={}
  counter =0
  s=s.lower()

  for i in s:
    if i in h:
      h[i]+=1
    else:
      h[i]=1

  for i in h:
    if h[i] % 2 == 1:
      counter +=1
      if counter > 1:
        return False

  return True


##Valid Palindrome 
Given a string, determine if it is a palindrome, considering only alphanumeric characters and ignoring cases.



In [ ]:
def ispalindrome(s):
  start  = 0
  end =len(s)-1
  s=s.lower()

  while start < end :
    while not s[start].isalnum() and start < end: # this is to handle spaces-- 'Race Car'
      start += 1

    while not s[end].isalnum() and start < end: # this is to handle spaces at the end -- 'Race Car '
      end -= 1

    if s[start] != s[end]:
      print (s[start])
      return False
    start += 1
    end -= 1

  return True

In [ ]:
ispalindrome('Race ca r ')

True

## Longest palindrome construct
Given a string, determine the length of the longest possible palindromic string that can be constructed using the characters of the string. 

In [ ]:
def palindromeconstruct(s):
  h={}
  counter =0
  maxodd_count=0
  second_highest = 0

  if len(s) == 1:
    return 1
  for i in s:
    if i in h:
      h[i]+=1
    else:
      h[i]=1

  for i in h:
    if h[i] % 2 == 0:
      counter += h[i]
    else:
      if h[i] > maxodd_count:
        maxodd_count = h[i]
        maxodd_char = i
  counter = counter + maxodd_count
  print(h)
  if maxodd_char and len(h)>1:
    h.pop(maxodd_char,None)
    print(h)
    for i in h:
      if h[i] % 2 != 0 and h[i]>1:
        if h[i] > second_highest:
          second_highest = h[i]
          counter=counter+second_highest-1

  return (counter)


In [ ]:
palindromeconstruct('aabbcccdddefgh')

{'a': 2, 'b': 2, 'c': 3, 'd': 3, 'e': 1, 'f': 1, 'g': 1, 'h': 1}
{'a': 2, 'b': 2, 'd': 3, 'e': 1, 'f': 1, 'g': 1, 'h': 1}


9

##Zigzag Conversion
Given a string s and an integer value rows return the "zigzag" encoding of s read off row-by-row.


In [ ]:
def zigzag(s,r):
  l=['']*r
  row = 0
  down = False

  for i in s:
    l[row]+=i

    if row == r-1 or row == 0:
      down = not down

    if down:
      row += 1
    
    else:
      row  -= 1
    
  ret =''
  for i in l:
    ret += i

  
  return ret





In [ ]:
zigzag('YELLOWPINK',4)

'YPEWILONLK'

In [ ]:
'YPEWILONLK' == zigzag('YELLOWPINK',4) 

True

In [ ]:
(zigzag('YELLOWPINK',4)).lower()

'ypewilonlk'

#Hourglass

In [ ]:
def hourglassSum(arr):
    sum = []


    for i in range(len(arr)-2):
        for j in range(len(arr)-2):
            sum.append(arr[i][j]+arr[i][j+1]+arr[i][j+2]+
            arr[i+1][j+1]+
            arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2])
        
    return(max(sum)) 

In [ ]:
def hourglasspractice(arr):
  sum =[]

  for i in range(len(arr)-2):
    for j in range(len(arr)-2):
      sum.append(arr[i][j]+arr[i][j+1]+arr[i][j+2]+
                 arr[i+1][j+1]+
                 arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2])
      
  return(max(sum))

In [ ]:
 t = [ [np.random.randint(10)]*6 for i in range(6)]  

In [ ]:
t

[[8, 8, 8, 8, 8, 8],
 [7, 7, 7, 7, 7, 7],
 [1, 1, 1, 1, 1, 1],
 [5, 5, 5, 5, 5, 5],
 [8, 8, 8, 8, 8, 8],
 [6, 6, 6, 6, 6, 6]]

In [ ]:
hourglasspractice(t)==hourglassSum(t)

True

In [ ]:
import json

# some JSON:
x =  '{ "name":"John", "age":30, "city":"New York"}'

# parse x:
y = json.loads(x)

# the result is a Python dictionary:
print(y["age"])

30


# Parse complex json files

# New Section

In [ ]:
import json

print(json.dumps({"name": "John", "age": 30}))
print(json.dumps(["apple", "bananas"]))
print(json.dumps(("apple", "bananas")))
print(json.dumps("hello"))
print(json.dumps(42))
print(json.dumps(31.76))
print(json.dumps(True))
print(json.dumps(False))
print(json.dumps(None))

{"name": "John", "age": 30}
["apple", "bananas"]
["apple", "bananas"]
"hello"
42
31.76
true
false
null


In [ ]:
import json

x = {
  "name": "John",
  "age": 30,
  "married": True,
  "divorced": False,
  "children": ("Ann","Billy"),
  "pets": None,
  "cars": [
    {"model": "BMW 230", "mpg": 27.5},
    {"model": "Ford Edge", "mpg": 24.1}
  ]
}

print(json.dumps(x))

{"name": "John", "age": 30, "married": true, "divorced": false, "children": ["Ann", "Billy"], "pets": null, "cars": [{"model": "BMW 230", "mpg": 27.5}, {"model": "Ford Edge", "mpg": 24.1}]}


In [ ]:
for i in x.items():
  print (i)

('name', 'John')
('age', 30)
('married', True)
('divorced', False)
('children', ('Ann', 'Billy'))
('pets', None)
('cars', [{'model': 'BMW 230', 'mpg': 27.5}, {'model': 'Ford Edge', 'mpg': 24.1}])


In [ ]:
example2 = {"order_id": 1234, "customer_id": 100, "line_items":
        [{"product_id": 5, "price": 5.99}, {"product_id": 10, "price": 20.99}]}

In [ ]:
example2=json.dumps(example2)

In [ ]:
l='price'
m=[]
curr_obj = example2
for i,j in curr_obj.items():
  if isinstance(j,dict):
   curr_obj = j
  if isinstance(j,list):
   for k in j:
     if l in k:
       m.append(k[l])
m

order_id
customer_id
line_items


[5.99, 20.99]

In [ ]:
def recursive_lookup(k, d):
    if k in d: return d
    for v in d.values():
        if isinstance(v, dict):
            a = recursive_lookup(k, v)
            if a is not None: return a
        if isinstance(v,list):
          for j in v:
            a = recursive_lookup(k, j)
            if a is not None: return a
    return None

In [ ]:
recursive_lookup('price',example2)

{'price': 5.99, 'product_id': 5}

In [ ]:
example2.values()

dict_values([1234, 100, [{'product_id': 5, 'price': 5.99}, {'product_id': 10, 'price': 20.99}]])

In [ ]:
def get_value(d, target):
  val = filter(None, [[b] if a == target else get_value(b) if isinstance(b, dict) else None for a, b in d.items()])
  return [i for b in val for i in b]

print(get_value(example2,'price'))

[]


In [ ]:
def myprint(d):
    for k, v in d.items():
        if isinstance(v, dict):
            myprint(v)
        elif isinstance(v,list):
            print(v)

        else:
            print("{0} : {1}".format(k, v))

In [ ]:
myprint(example2)

order_id : 1234
customer_id : 100
[{'product_id': 5, 'price': 5.99}, {'product_id': 10, 'price': 20.99}]


In [ ]:
for k,v in example2.items():
  print(type(v))

<class 'int'>
<class 'int'>
<class 'list'>


In [ ]:
Dict = { 'Dict1': {1: 'G', 2: 'F', 3: 'G'},  
         'Dict2': {'Name': 'Geeks', 1: [1, 2]} } 

In [ ]:
myprint(Dict)

1 : G
2 : F
3 : G
Name : Geeks
[1, 2]


#Contains Duplicate

In [ ]:
def checkduplicate(nums):
  nums=sorted(nums)
  h={}
  check=0

  for i in nums:
    if i in h:
      h[i]+=1
      return True
    else:
      h[i]=1

  return False


In [ ]:
checkduplicate([1,2,3,4,5])

False

#Buy/Sell Stocks

In [1]:
def buysell(nums):
  if len(nums) < 2:
    return 0

  buy=nums[0]
  profit = 0

  for i in nums[1:]:
    if i-buy > profit:
      profit =i-buy

    elif i< buy:
      buy = i

  return profit

In [4]:
buysell([7,1,5,3,6,4])

5

#Buy/Sell Stocks Consecutive days

In [7]:
def buysellconsecutive(nums):
  if len(nums) <2 :
    return 0

  profit = 0

  for i in range(len(nums)-1):
    if nums[i] < nums[i+1]:
      profit += nums[i+1] - nums[i]
  
  return profit

In [8]:
buysellconsecutive([7,1,5,3,6,4])

7